### ISSUE TITLE
第四章第二节使用restTemplate找不到USERSERVICE

### ISSUE THREAD

**Issue by qzing** [cd826/springcloud-demo#5]
### 但是在Eureka中可以看到两个服务均已注册，尝试将getForEntity函数中的参数USERSERVICE直接替换为ip+端口号可以正常看到用户评论。报错如下：
2019-12-25 21:30:22.413 ERROR 19228 --- [nio-2200-exec-7] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.web.client.ResourceAccessException: I/O error on GET request for "http://USERSERVICE/users/1": USERSERVICE; nested exception is java.net.UnknownHostException: USERSERVICE] with root cause    

java.net.UnknownHostException: USERSERVICE
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_212]
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172) ~[na:1.8.0_212]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_212]
        at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_212]
        at java.net.Socket.connect(Socket.java:538) ~[na:1.8.0_212]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_212]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_212]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_212]
        at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:78) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]
        at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53) ~[spring-web-4.3.7.RELEASE.jar:4.3.7.RELEASE]

**Comment by qzing** [comment]
在restTemplate的bean前加@LoadBalanced注释
